### ISSUE TITLE
issues on current architecture

### ISSUE THREAD

**Issue by leondgarse** [FlyEgle/CMT-pytorch#4]
- 根据论文的描述以及图示中，与当前实现不同的地方：
  - `LightMultiHeadSelfAttention` 中 `self.sr = nn.Conv2d(...)` 应该是 `DW Conv`。 这里使用 `DW` 的话，总体的参数量应该可以接近论文中的描述。
  - `InvertedResidualFeedForward` 中 DW 部分应该类似 `F(X) = Norm(GELU(DWConv(X) + X))`，当前的实现类似 `F(X) = Norm(GELU(DWConv(X))) + X`。
  - 论文中的描述，每个 stage 降采样的 `Conv2D` 后面有一个 `layer_norm`。

- 另外不确定的地方：
  - 接触到的很多网络模型，一般 conv2d 中不使用 `bias`，不知道作者这里是用的什么。@ggjy
- 我大概写了 Tensorflow 的实现 [Keras CMT](https://github.com/leondgarse/keras_cv_attention_models/tree/main/keras_cv_attention_models/cmt)，`RelativePostional` 部分还没写。有时间也训练一下试试，最近写的几个模型 `Halonet` / `CoAtNet` 什么的训练都占用显存很大，不好跑啊。

**Comment by FlyEgle** [comment]
1. dw不好训练，速度慢。
2. 残差连接，为啥要对shortcut做norm，不觉得很奇怪吗，你看ResNet结构，为了更好的收敛，所以直接x相加，MBv2也是如此。
3. 降采样加什么layernorm，这里是卷积下采样。
4. bias不用是因为后面有bn，就相当于加了bias。conv，bn是可以fuse的，你去推算一下就懂了

**Comment by FlyEgle** [comment]
至于你的PR，你可以先跑一下，要是work了，我在merge，跑一次时间比较长。
