### ISSUE TITLE
ImportError: cannot import name '_pil_interp' from 'timm.data.transforms'

### ISSUE THREAD

**Issue by wang-qin123** [FlyEgle/CMT-pytorch#6]
您好，出现报错如题，timm.data.transformers.py中也没有看到_pil_interp方法，请问怎么解决呢，您用的哪个版本的timm呢

**Comment by FlyEgle** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/26165705/165433093-be671fd2-29dd-4391-b309-c3c250b502f7.png">
我用的是这个版本

**Comment by wang-qin123** [comment]
谢谢，确实用timm=0.4.12就好了，pytorch版本也要对应

**Comment by Joe-Hall-Lee** [comment]
将_pil_interp改为str_to_pil_interp。
